import os
import io
import base64
import logging
import uuid

from django.core.files.base import ContentFile

logger = logging.getLogger(__name__)

AI_PROVIDER = os.getenv('AI_PROVIDER', 'google').lower()

if AI_PROVIDER == 'google':
    from google import genai
    from google.genai.types import GenerateContentConfig

    google_client = genai.Client(api_key=os.getenv('GOOGLE_API_KEY'))


def generate_post_text(topic: str, tone: str = 'professional', extra_instructions: str = '') -> str:
    """Generate a LinkedIn post using Gemini."""
    system_instruction = (
        "You are an expert LinkedIn content writer. You create engaging, "
        "professional posts that drive engagement and provide value. "
        "Write the post text only — no titles, no labels, no markdown formatting. "
        "Use line breaks for readability. Include relevant emojis sparingly. "
        "End with a call-to-action or thought-provoking question when appropriate."
    )

    user_prompt = f"""Write a LinkedIn post about: {topic}

Tone: {tone}
{f'Additional instructions: {extra_instructions}' if extra_instructions else ''}

Requirements:
- Keep it between 150-300 words
- Use short paragraphs and line breaks for readability
- Include 3-5 relevant hashtags at the end
- Make it engaging and authentic"""

    model = os.getenv('GOOGLE_MODEL', 'gemini-2.5-flash-preview-04-17')

    response = google_client.models.generate_content(
        model=model,
        contents=user_prompt,
        config=GenerateContentConfig(
            system_instruction=system_instruction,
            max_output_tokens=2000,
            temperature=0.8,
        ),
    )
    return response.text.strip()


def generate_image(prompt: str) -> tuple[bytes, str]:
    """Generate an image using Gemini image model. Returns (image_bytes, filename)."""
    image_model = 'gemini-3.1-flash-image-preview'

    full_prompt = (
        f"Generate a professional, visually appealing image suitable for a LinkedIn post. "
        f"The image should be: {prompt}"
    )

    response = google_client.models.generate_content(
        model=image_model,
        contents=full_prompt,
        config=GenerateContentConfig(
            response_modalities=['Text', 'Image'],
        ),
    )

    for part in response.candidates[0].content.parts:
        if part.inline_data is not None:
            image_bytes = part.inline_data.data
            mime = part.inline_data.mime_type
            ext = 'png' if 'png' in mime else 'jpg'
            filename = f'ai_{uuid.uuid4().hex[:12]}.{ext}'
            return image_bytes, filename

    raise ValueError('No image was generated by the model.')


def save_generated_image(post, image_bytes: bytes, filename: str, prompt: str):
    """Save AI-generated image bytes as a PostImage."""
    from .models import PostImage

    post_image = PostImage(
        post=post,
        alt_text=prompt[:500],
        prompt=prompt,
        is_ai_generated=True,
    )
    post_image.image.save(filename, ContentFile(image_bytes), save=True)
    return post_image


def publish_post(post):
    """Publish a post to LinkedIn."""
    from .models import PostStatus
    from linkedin.services import create_text_post, create_image_post
    from django.utils import timezone

    account = post.linkedin_account
    if not account or not account.is_active:
        post.status = PostStatus.FAILED
        post.error_message = 'No active LinkedIn account linked to this post.'
        post.save()
        return

    if not account.is_token_valid():
        post.status = PostStatus.FAILED
        post.error_message = 'LinkedIn access token has expired. Please reconnect.'
        post.save()
        return

    post.status = PostStatus.PUBLISHING
    post.save()

    try:
        first_image = post.images.first()
        if first_image:
            with first_image.image.open('rb') as f:
                image_bytes = f.read()
            result = create_image_post(
                access_token=account.access_token,
                linkedin_person_id=account.linkedin_id,
                text=post.content,
                image_bytes=image_bytes,
                alt_text=first_image.alt_text,
            )
        else:
            result = create_text_post(
                access_token=account.access_token,
                linkedin_person_id=account.linkedin_id,
                text=post.content,
            )

        post.linkedin_post_id = result.get('post_id', '')
        post.status = PostStatus.PUBLISHED
        post.published_at = timezone.now()
        post.error_message = ''
    except Exception as exc:
        logger.exception('Failed to publish post %s', post.id)
        post.status = PostStatus.FAILED
        post.error_message = str(exc)[:1000]

    post.save()
